### ISSUE TITLE
Set up analytics

### ISSUE THREAD

**Issue by ErikBjare** [kursval/kursval.github.io#4]
Setting up some kind of analytics (preferably public) would be really fun, was thinking about linking it but I want to know how many people already use it.

You may label this with "feature" or as appropriate.

**Comment by ErikBjare** [comment]
If nobody else wants to do it I can get it done, but I want approval before I get started so my later PR isn't rejected, making the effort without use.

**Comment by alfredakesson** [comment]
I invited you to the project so you can commit your changes directly. We, the creators of the project, has already taken our exams and are not so much in the loop of course picking, and we will probably not commit any more. So feel free to invete others and continue developing the course pricking application, if you want.

**Comment by ErikBjare** [comment]
@alfredakesson Awesome, thanks! Would you mind making me an owner so I can 'carry on the torch' properly in that case?

**Comment by ErikBjare** [comment]
@alfredakesson @jensgustafsson I noticed you already have the Google Analytics script thingy in `index.html`, do you mind if I change it to my own tracking code?
